munin-pihole-plugins: add option to display full GNU GPL v3, 07.15.00
Changes to be committed:
 - modified:   etc/bash_completion.d/munin-pihole-plugins
   bump version to 07.15.00
   MUNIN_VERSION is now MUNIN_BRANCH
   add -g,gnu-gpl,--gnu-gpl completions for -s,show,--show command
 - modified:   script/munin-pihole-plugins
   bump version to 07.15.00
   add 'less' to script_dependencies
   (it was previously used optimistically)
   add -g,gnu-gpl,--gnu-gpl extention to -s,show,--show command
   (display full GNU GPL v3 license text with pagination)
   show header and runtime disclaimer in child scripts
 - modified:   usr/share/munin/plugins/pihole_
   bump version to 07.15.00
   (no functional changes)

diff --git a/script/munin-pihole-plugins b/script/munin-pihole-plugins
--- a/script/munin-pihole-plugins
+++ b/script/munin-pihole-plugins
@@ -17,7 +17,7 @@
 
 # munin-pihole-plugins version
 # must follow 8 character major.minor.micro scheme
-VERSION="07.14.03"
+VERSION="07.15.00"
 
 # source any external variables from munin-pihole-plugins.conf
 # somewhat of a security risk honestly, i don't particularly
@@ -45,10 +45,10 @@ install_plugins="${INSTALL_PLUGINS:-true}"
 install_script="${INSTALL_SCRIPT:-true}"
 install_webserver="${INSTALL_WEBSERVER:-true}"
 lighttpd_webroot="${LIGHTTPD_WEBROOT:-/var/www/html}"
+munin_branch="${MUNIN_BRANCH:-stable}"
 munin_dir="${MUNIN_DIR:-/etc/munin}"
 munin_config_dir="${MUNIN_CONFIG_DIR:-${munin_dir}/munin-conf.d}"
 munin_plugin_dir="${MUNIN_PLUGIN_DIR:-/usr/share/munin/plugins}"
-munin_version="${MUNIN_VERSION:-stable}"
 node_plugin_dir="${NODE_PLUGIN_DIR:-${munin_dir}/plugins}"
 plugin_config_dir="${PLUGIN_CONFIG_DIR:-${munin_dir}/plugin-conf.d}"
 plugin_list="${PLUGIN_LIST:-blocked cache cache_by_type clients percent queries replies_by_type status unique_domains}"
@@ -66,10 +66,11 @@ verbosity_level="${VERBOSITY_LEVEL:-3}"
 # values for *_dependencies and *_services are intentional
 # and must be retained for the sake of easy string concat
 current_dir="$(dirname "$(readlink -f "$0")")"
+gnu_gpl_v3="https://raw.githubusercontent.com/saint-lascivious/munin-pihole-plugins/development/LICENSE.md"
 plugin_dependencies="curl munin-node "
 plugin_services="munin-node "
 proxy_repo="https://raw.githubusercontent.com/saint-lascivious/lighttpd-external-munin-proxy"
-script_dependencies="init-system-helpers wget "
+script_dependencies="init-system-helpers less wget "
 terminal_height="$(stty size | cut -d " " -f1)"
 terminal_width="$(stty size | cut -d " " -f2)"
 webserver_dependencies="lighttpd munin "
@@ -199,6 +200,8 @@ fi
 
 # a simple self update function for the munin-pihole-plugins script
 update_now() {
+    reverberate "header"
+    gnugpl_info_function "runtime_disclaimer"
     reverberate "info" "Updating the munin-pihole-plugins script"
     download "${plugin_domain}" -O "${current_dir}/munin-pihole-plugins"
     if [[ "${verbosity_level}" -ge "4" ]]; then
@@ -427,17 +430,19 @@ configure_proxy() {
             fi
         fi
         reverberate "info" "Installing Munin webserver lighttpd proxy configuration"
-        if [[ "${munin_version}" == "stable" ]]; then
+        if [[ "${munin_branch}" == "stable" ]]; then
             download "${proxy_repo}/master/etc/lighttpd/external.conf" -O "${proxy_config}"
         else
-            if [[ "${munin_version}" == "latest" ]]; then
+            if [[ "${munin_branch}" == "latest" ]]; then
                 download "${proxy_repo}/latest/etc/lighttpd/external.conf" -O "${proxy_config}"
             else
-                reverberate "error" "Invalid Munin version"
-                reverberate "failure" "${munin_version}"
-                reverberate "info" "Valid Munin versions are"
-                reverberate "success" "latest"
-                reverberate "success" "stable"
+                reverberate "error" "Invalid Munin branch"
+                reverberate "failure" "${munin_branch}"
+                if [[ "${verbosity_level}" -ge "4" ]]; then
+                    reverberate "info" "Valid Munin branches are"
+                    reverberate "success" "latest"
+                    reverberate "success" "stable"
+                fi
                 reverberate "exit"
                 exit 1
             fi
@@ -684,6 +689,8 @@ fi
 # hence the reasoning for leaving the hardcoded config dir/file path
 # intact here rather than following variables
 uninstall_now() {
+    reverberate "header"
+    gnugpl_info_function "runtime_disclaimer"
     if [[ -f "/etc/bash_completion.d/munin-pihole-plugins" ]]; then
         reverberate "info" "Uninstalling the munin-pihole-plugins bash completion script"
         rm "/etc/bash_completion.d/munin-pihole-plugins" || return
@@ -691,11 +698,19 @@ uninstall_now() {
             reverberate "success" "/etc/bash_completion.d/munin-pihole-plugins removed"
         fi
     fi
-    if [[ -d "/etc/munin-pihole-plugins" ]]; then
-        reverberate "info" "Removing the munin-pihole-plugins external configuration directory"
-        rm -fr "/etc/munin-pihole-plugins" || return
+    if [[ -f "${external_config_dir}/${external_config_file}" ]]; then
+        reverberate "info" "Removing munin-pihole-plugins external configuration"
+        rm "${external_config_dir}/${external_config_file}" || return
         if [[ "${verbosity_level}" -ge "4" ]]; then
-            reverberate "success" "/etc/munin-pihole-plugins removed"
+            reverberate "success" "${external_config_dir}/${external_config_file} removed"
+        fi
+    fi
+    if [[ "$(ls -A "${external_config_dir}")" ]]; then
+        reverberate "info" "munin-pihole-plugins external configuration is empty"
+        reverberate "info" "Removing munin-pihole-plugins external configuration directory"
+        rm "${external_config_dir}/${external_config_file}" || return
+        if [[ "${verbosity_level}" -ge "4" ]]; then
+            reverberate "success" "${external_config_dir} removed"
         fi
     fi
     if [[ -f "$(script_dir)/munin-pihole-plugins" ]]; then
@@ -820,7 +835,7 @@ EOF
 config_function() {
     min_height="3"
     if [[ -n "$3" ]]; then
-        external_var_list="BRANCH DNS_PORT DNS_SERVER EXTERNAL_CONFIG_DIR EXTERNAL_CONFIG_FILE IGNORE_PIHOLE_ON_HOST INSTALL_PLUGINS INSTALL_SCRIPT INSTALL_WEBSERVER LIGHTTPD_WEBROOT MUNIN_DIR MUNIN_CONFIG_DIR MUNIN_PLUGIN_DIR MUNIN_VERSION NODE_PLUGIN_DIR PLUGIN_CONFIG_DIR PLUGIN_LIST PROXY_CONFIG_DIR SCRIPT_DIR SHOW_COLOUR SHOW_HEADER SKIP_DEPENDENCY_CHECK UPDATE_SELF VERBOSITY_LEVEL"
+        external_var_list="BRANCH DNS_PORT DNS_SERVER EXTERNAL_CONFIG_DIR EXTERNAL_CONFIG_FILE IGNORE_PIHOLE_ON_HOST INSTALL_PLUGINS INSTALL_SCRIPT INSTALL_WEBSERVER LIGHTTPD_WEBROOT MUNIN_BRANCH MUNIN_DIR MUNIN_CONFIG_DIR MUNIN_PLUGIN_DIR NODE_PLUGIN_DIR PLUGIN_CONFIG_DIR PLUGIN_LIST PROXY_CONFIG_DIR SCRIPT_DIR SHOW_COLOUR SHOW_HEADER SKIP_DEPENDENCY_CHECK UPDATE_SELF VERBOSITY_LEVEL"
         for external_var_id in ${external_var_list}; do
             if [[ "$2" == "${external_var_id}" ]]; then
                 if [[ -f "${script_dir}/munin-pihole-plugins" ]]; then
@@ -935,6 +950,9 @@ Type \"munin-pihole-plugins --install --script\" to install it now"
             "LIGHTTPD_WEBROOT")
                 some "LIGHTTPD_WEBROOT: ${lighttpd_webroot}"
             ;;
+            "MUNIN_BRANCH")
+                some "MUNIN_BRANCH: ${munin_branch}"
+            ;;
             "MUNIN_DIR")
                 some "MUNIN_DIR: ${munin_dir}"
             ;;
@@ -943,9 +961,6 @@ Type \"munin-pihole-plugins --install --script\" to install it now"
             ;;
             "MUNIN_PLUGIN_DIR")
                 some "MUNIN_PLUGIN_DIR: ${munin_plugin_dir}"
-            ;;
-            "MUNIN_VERSION")
-                some "MUNIN_VERSION: ${munin_version}"
             ;;
             "NODE_PLUGIN_DIR")
                 some "NODE_PLUGIN_DIR: ${node_plugin_dir}"
@@ -1010,10 +1025,10 @@ Type \"munin-pihole-plugins --install --script\" to install it now"
  INSTALL_SCRIPT=\"${install_script}\"
  INSTALL_WEBSERVER=\"${install_webserver}\"
  LIGHTTPD_WEBROOT=\"${lighttpd_webroot}\"
+ MUNIN_BRANCH=\"${munin_branch}\"
  MUNIN_DIR=\"${munin_dir}\"
  MUNIN_CONFIG_DIR=\"${munin_config_dir}\"
  MUNIN_PLUGIN_DIR=\"${munin_plugin_dir}\"
- MUNIN_VERSION=\"${munin_version}\"
  NODE_PLUGIN_DIR=\"${node_plugin_dir}\"
  PLUGIN_CONFIG_DIR=\"${plugin_config_dir}\"
  PLUGIN_LIST=\"${plugin_list}\"
@@ -1159,6 +1174,12 @@ install using the PLUGIN_LIST variable.
 \\nDisplay munin-pihole-plugins GNU GPL licensing conditions.
 \\nExample: \"munin-pihole-plugins $2 --conditions\""
                 ;;
+                "-g" | "gnu-gpl" | "--gnu-gpl")
+                    min_height="6"
+                    some "Usage: munin-pihole-plugins {$2 [PARAMETER]}
+\\nDisplay the full GNU GPL v3 license text.
+\\nExample: \"munin-pihole-plugins $2 --gnu-gpl\""
+                ;;
                 "-l" | "liability" | "--liability")
                     min_height="6"
                     some "Usage: munin-pihole-plugins {$2 [PARAMETER]}
@@ -1176,6 +1197,7 @@ install using the PLUGIN_LIST variable.
                     some "Usage: munin-pihole-plugins {$2 [PARAMETER]}
 \\nOption\\t\\t    GNU long option\\tMeaning
  -c, conditions\\t     --conditions\\t Show GNU GPLv3 licensing conditions
+ -g, gnu-gpl\\t     --gnu-gpl\\t\\t Show full GNU GPL v3 license text
  -l, liability\\t     --liability\\t Show liability definition
  -w, warranty\\t     --warranty\\t\\t Show warranty information
 \\nExample: \"munin-pihole-plugins $2 --warranty\""
@@ -1324,7 +1346,7 @@ install_function() {
                 fi
             fi
             obnoxious_header
-            gnugpl_info_function
+            gnugpl_info_function "runtime_disclaimer"
             if [[ "${skip_dependency_check}" == "false" ]]; then
                 install_dependencies
             else
@@ -1346,7 +1368,7 @@ install_function() {
                 reverberate "info" "Skipping plugin installation"
             fi
             if [[ "${install_webserver}" == "true" ]]; then
-                if [[ "${munin_version}" == "stable" ]]; then
+                if [[ "${munin_branch}" == "stable" ]]; then
                     configure_munin
                 fi
                 configure_proxy
@@ -1382,6 +1404,16 @@ gnugpl_info_function() {
   GNU General Public License for more details.
 \\nContact: munin-pihole-plugins@sainternet.xyz"
         ;;
+        "-g" | "gnu-gpl" | "--gnu-gpl")
+            download "${gnu_gpl_v3}" -O "${temp_dir}/.munin-pihole-plugins_license"
+            if i_can_haz less; then
+                less "${temp_dir}/.munin-pihole-plugins_license"
+            else
+                if i_can_haz more; then
+                    more "${temp_dir}/.munin-pihole-plugins_license"
+                fi
+            fi
+        ;;
         "-l" | "liability" | "--liability")
             min_height="14"
             some "munin-pihole-plugins saint-lascivious (Hayden Pearce) ©2022
@@ -1409,7 +1441,7 @@ gnugpl_info_function() {
   ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
 \\nContact: munin-pihole-plugins@sainternet.xyz"
         ;;
-        "")
+        "runtime_disclaimer")
             if [[ "${verbosity_level}" -ge "1" ]]; then
                 if [[ -f "${script_dir}/munin-pihole-plugins" ]]; then
                     example_prefix="munin-pihole-plugins"
@@ -1468,7 +1500,7 @@ uninstall_function() {
             fi
             check_privilege "$@"
             obnoxious_header
-            gnugpl_info_function
+            gnugpl_info_function "runtime_disclaimer"
             if [[ "${install_plugins}" == "true" ]]; then
                 dependency_list+="munin-node "
                 if [[ -d "${plugin_config_dir}" ]]; then
