munin-pihole-plugins: feature creep follow-up to 42cfae0
avoid editing munin.conf directly if we can, add a help-like function to print current values of environment variables eligible for override

Changes to be committed:
 - modified:   README.md
   update --help text
 - modified:   script/munin-pihole-plugins
   bump script version to 1.5
   separate munin_dir from munin_config_dir
   fix inconsistently wacky formatting (now consistently wacky)
   use munin-conf.d config fragment to set *_strategy if possible
   only modify munin.conf directly as a fallback, warn if we do
   add -V, --variables function to clarify script configuration

diff --git a/script/munin-pihole-plugins b/script/munin-pihole-plugins
--- a/script/munin-pihole-plugins
+++ b/script/munin-pihole-plugins
@@ -5,10 +5,11 @@
 # saint@sainternet.xyz
 
 install_webserver="${INSTALL_WEBSERVER:-true}"
-munin_config_dir="${MUNIN_CONFIG_DIR:-/etc/munin}"
+munin_dir="${MUNIN_DIR:-/etc/munin}"
+munin_config_dir="${MUNIN_CONFIG_DIR:-$munin_dir/munin-conf.d}"
 munin_plugin_dir="${MUNIN_PLUGIN_DIR:-/usr/share/munin/plugins}"
-node_plugin_dir="${NODE_PLUGIN_DIR:-$munin_config_dir/plugins}"
-plugin_config_dir="${PLUGIN_CONFIG_DIR:-$munin_config_dir/plugin-conf.d}"
+node_plugin_dir="${NODE_PLUGIN_DIR:-$munin_dir/plugins}"
+plugin_config_dir="${PLUGIN_CONFIG_DIR:-$munin_dir/plugin-conf.d}"
 plugin_list="${PLUGIN_LIST:-blocked cache cache_by_type clients percent queries replies_by_type status unique_domains}"
 proxy_config_dir="${PROXY_CONFIG_DIR:-/etc/lighttpd}"
 skip_dependency_check="${SKIP_DEPENDENCY_CHECK:-false}"
@@ -18,7 +19,7 @@ plugin_repo="https://raw.githubusercontent.com/saint-lascivious/munin-pihole-plu
 plugin_services="munin-node"
 proxy_repo="https://raw.githubusercontent.com/saint-lascivious/lighttpd-external-munin-proxy/master"
 script_dependencies="init-system-helpers wget"
-script_version="1.4"
+script_version="1.5"
 webserver_dependencies="lighttpd munin"
 webserver_services="lighttpd munin"
 
@@ -64,14 +65,14 @@ install_dependencies() {
 configure_proxy() {
     if [[ -d "$proxy_config_dir" ]]; then
         if [[ -s "$proxy_config_dir/external.conf" ]]; then
-            mv "$proxy_config_dir"/external.conf "$proxy_config_dir"/external.conf.bak || return
+            mv "$proxy_config_dir/external.conf" "$proxy_config_dir/external.conf.bak" || return
             echo -e " * \\e[32;1m[INFO]\\e[0m Existing lighttpd external.conf backed up to"
-            echo "$proxy_config_dir"/external.conf.bak
+            echo "$proxy_config_dir/external.conf.bak"
         else
-            rm "$proxy_config_dir"/external.conf || return
+            rm "$proxy_config_dir/external.conf" || return
         fi
         if [[ -x "$(command -v wget)" ]]; then
-            wget -q --show-progress "$proxy_repo$proxy_config_dir"/external.conf -P "$proxy_config_dir"
+            wget -q --show-progress "$proxy_repo/etc/lighttpd/external.conf" -P "$proxy_config_dir"
         else
             echo -e " * \\e[31;1m[ERROR]\\e[0m The required package 'wget' was not found"
             exit 1
@@ -87,17 +88,34 @@ configure_proxy() {
 
 configure_munin() {
     if [[ -d "$munin_config_dir" ]]; then
-        if [[ -f "$munin_config_dir"/munin.conf ]]; then
-            sed -i "s/#html_strategy cron/html_strategy cgi/g" "$munin_config_dir"/munin.conf
-            sed -i "s/#graph_strategy cron/graph_strategy cgi/g" "$munin_config_dir"/munin.conf
-        else
-            echo -e " * \\e[31;1m[ERROR]\\e[0m No Munin configuration file found at"
-            echo "$munin_config_dir/munin.conf"
-            echo -e " * \\e[32;1m[INFO]\\e[0m If this file is located at a different path try"
-            echo "export MUNIN_CONFIG_DIR=\"/path/to/file\""
-            exit 1
+        if [[ ! -f "$munin_config_dir/99-graph-strategy.conf" ]]; then
+            if [[ -x "$(command -v wget)" ]]; then
+                wget -q --show-progress "$plugin_repo/etc/munin/munin-conf.d/99-graph-strategy.conf" -P "$munin_config_dir" || return
+            else
+                echo -e " * \\e[31;1m[ERROR]\\e[0m The required package 'wget' was not found"
+                exit 1
+            fi
         fi
     else
+        echo -e " * \\e[33;1m[WARNING]\\e[0m Attempting fallback configuration editing munin.conf directly"
+        if [[ -d "$munin_dir" ]]; then
+            if [[ -f "$munin_dir/munin.conf" ]]; then
+                sed -i "s/#html_strategy cron/html_strategy cgi/g" "$munin_dir/munin.conf"
+                sed -i "s/#graph_strategy cron/graph_strategy cgi/g" "$munin_dir/munin.conf"
+            else
+                echo -e " * \\e[31;1m[ERROR]\\e[0m No munin.conf file found at"
+                echo "$munin_dir/munin.conf"
+                echo -e " * \\e[32;1m[INFO]\\e[0m If this file is located at a different path try"
+                echo "export MUNIN_DIR=\"/path/to/directory\""
+                exit 1
+            fi
+        else
+            echo -e " * \\e[31;1m[ERROR]\\e[0m No Munin directory found at"
+            echo "$munin_dir"
+            echo -e " * \\e[32;1m[INFO]\\e[0m If this directory is located at a different path try"
+            echo "export MUNIN_DIR=\"/path/to/directory\""
+            exit 1
+        fi
         echo -e " * \\e[31;1m[ERROR]\\e[0m No Munin configuration directory found at"
         echo "$munin_config_dir"
         echo -e " * \\e[32;1m[INFO]\\e[0m If this directory is located at a different path try"
@@ -109,8 +127,8 @@ configure_munin() {
 remove_existing() {
     if [[ -d "$munin_plugin_dir" ]]; then
         for plugin_id in $plugin_list; do
-            if [[ -f "$munin_plugin_dir"/pihole_"$plugin_id" ]]; then
-                rm "$munin_plugin_dir"/pihole_"$plugin_id" || return
+            if [[ -f "$munin_plugin_dir/pihole_$plugin_id" ]]; then
+                rm "$munin_plugin_dir/pihole_$plugin_id" || return
             fi
         done
     else
@@ -136,13 +154,13 @@ install_plugins() {
         if [[ -d "$node_plugin_dir" ]]; then
             for plugin_id in $plugin_list; do
                 if [[ -x "$(command -v wget)" ]]; then
-                    wget -q --show-progress "$plugin_repo$munin_plugin_dir/pihole_$plugin_id" -P "$munin_plugin_dir" || return
+                    wget -q --show-progress "$plugin_repo/usr/share/munin/plugins/pihole_$plugin_id" -P "$munin_plugin_dir" || return
                 else
                     echo -e " * \\e[31;1m[ERROR]\\e[0m The required package 'wget' was not found"
                     exit 1
                 fi
-                chmod +x "$munin_plugin_dir"/pihole_"$plugin_id" || return
-                ln -s "$munin_plugin_dir"/pihole_"$plugin_id" "$node_plugin_dir"/pihole_"$plugin_id" || return
+                chmod +x "$munin_plugin_dir/pihole_$plugin_id" || return
+                ln -s "$munin_plugin_dir/pihole_$plugin_id" "$node_plugin_dir/pihole_$plugin_id" || return
             done
         else
             echo -e " * \\e[31;1m[ERROR]\\e[0m No Munin node plugin directory found at"
@@ -164,7 +182,7 @@ configure_plugins() {
     if [[ -d "$plugin_config_dir" ]]; then
         if [[ ! -f  "$plugin_config_dir/pihole" ]]; then
             if [[ -x "$(command -v wget)" ]]; then
-                wget -q --show-progress "$plugin_repo$plugin_config_dir"/pihole -P "$plugin_config_dir"
+                wget -q --show-progress "$plugin_repo/etc/munin/plugin-conf.d/pihole" -P "$plugin_config_dir"
                 echo -e " * \\e[32;1m[INFO]\\e[0m Default plugin configuration saved to"
                 echo "$plugin_config_dir/pihole"
             else
@@ -212,16 +230,11 @@ Where \\e[33;1mOPTION\\e[0m is \\e[31;1mone\\e[0m of
     \\e[33;1m-v, --version\\e[0m        Display the munin-pihole-plugins script version
                          Current munin-pihole-plugins script version v$script_version
 
-    Set the \\e[31;1mPLUGIN_LIST\\e[0m variable to override the default plugin list:
-    \"blocked cache cache_by_type clients percent queries replies_by_type
-    status unique_domains\"
+    \\e[33;1m-V, --variables\\e[0m      Display a list of environment variables used by
+                         munin-pihole-plugins and their current values, which
+                         can be overridden using:
 
-    Example: export \\e[31;1mPLUGIN_LIST\\e[0m=\"blocked clients replies_by_type\"
-
-    Set the \\e[31;1mINSTALL_WEBSERVER\\e[0m variable to any value other than \"true\" to skip
-    installation of the Munin webserver, useful for adding additional nodes
-
-    Example: export \\e[31;1mINSTALL_WEBSERVER\\e[0m=\"false\""
+                         export \\e[33;1mVARIABLE\\e[0m=\"\\e[31;1mvalue\\e[0m\""
 }
 
 install_function() {
@@ -248,14 +261,14 @@ uninstall_function() {
     obnoxious_header
     remove_existing
     if [[ -d "$proxy_config_dir" ]]; then
-        if [[ -f "$proxy_config_dir"/external.conf.bak ]]; then
-            mv "$proxy_config_dir"/external.conf.bak "$proxy_config_dir"/external.conf || return
+        if [[ -f "$proxy_config_dir/external.conf.bak" ]]; then
+            mv "$proxy_config_dir/external.conf.bak" "$proxy_config_dir/external.conf" || return
             echo -e " * \\e[32;1m[INFO]\\e[0m Original lighttpd external.conf restored from"
-            echo "$proxy_config_dir"/external.conf.bak
+            echo "$proxy_config_dir/external.conf.bak"
         else
-            if [[ -f "$proxy_config_dir"/external.conf ]]; then
-                rm "$proxy_config_dir"/external.conf || return
-                touch "$proxy_config_dir"/external.conf
+            if [[ -f "$proxy_config_dir/external.conf" ]]; then
+                rm "$proxy_config_dir/external.conf" || return
+                touch "$proxy_config_dir/external".conf
             fi
         fi
     else
@@ -272,6 +285,29 @@ update_function() {
 
 version_function() {
     echo "munin-pihole-plugins v$script_version"
+}
+
+variable_function() {
+    echo -e "Usage: export \\e[33;1mVARIABLE\\e[0m=\"\\e[31;1mvalue\\e[0m\"
+
+    \\e[33;1mINSTALL_WEBSERVER\\e[0m=\"\\e[31;1m$install_webserver\\e[0m\"
+
+    \\e[33;1mMUNIN_DIR\\e[0m=\"\\e[31;1m$munin_dir\\e[0m\"
+
+    \\e[33;1mMUNIN_CONFIG_DIR\\e[0m=\"\\e[31;1m$munin_config_dir\\e[0m\"
+
+    \\e[33;1mMUNIN_PLUGIN_DIR\\e[0m=\"\\e[31;1m$munin_plugin_dir\\e[0m\"
+
+    \\e[33;1mNODE_PLUGIN_DIR\\e[0m=\"\\e[31;1m$node_plugin_dir\\e[0m\"
+
+    \\e[33;1mPLUGIN_CONFIG_DIR\\e[0m=\"\\e[31;1m$plugin_config_dir\\e[0m\"
+
+    \\e[33;1mPLUGIN_LIST\\e[0m=\"\\e[31;1m$plugin_list\\e[0m\"
+
+    \\e[33;1mPROXY_CONFIG_DIR\\e[0m=\"\\e[31;1m$proxy_config_dir\\e[0m\"
+
+    \\e[33;1mSKIP_DEPENDENCY_CHECK\\e[0m=\"\\e[31;1m$skip_dependency_check\\e[0m\""
+
 }
 
 if [[ ! "$EUID" -eq "0" ]];then
@@ -291,5 +327,6 @@ case "${1}" in
     "-u" | "--uninstall"    ) uninstall_function ;;
     "-U" | "--update"       ) update_function ;;
     "-v" | "--version"      ) version_function ;;
+    "-V" | "--variables"    ) variable_function ;;
     *                       ) help_function ;;
 esac
