munin-pihole-plugins: i can haz cheezburger, 07.13.00
break out command test-before-use case to its own function
should have happened from the beginning, but, oh well
it happened now

basic function:

if i_can_haz package-name; then
   we do stuff
fi

Changes to be committed:
 - modified:   etc/bash_completion.d/munin-pihole-plugins
   bump version to 07.13.00
   (no functional changes)
 - modified:   script/munin-pihole-plugins
   bump version to 07.13.00
   implement i_can_haz function for command test-before-use flow
   (allows for the removal of some now needless duplication)
 - modified:   usr/share/munin/plugins/pihole_
   bump version to 07.13.00
   (no functional changes)

diff --git a/script/munin-pihole-plugins b/script/munin-pihole-plugins
--- a/script/munin-pihole-plugins
+++ b/script/munin-pihole-plugins
@@ -17,7 +17,7 @@
 
 # munin-pihole-plugins version
 # must follow 8 character major.minor.micro scheme
-VERSION="07.12.02"
+VERSION="07.13.00"
 
 # source any external variables from munin-pihole-plugins.conf
 # somewhat of a security risk honestly, i don't particularly
@@ -144,6 +144,19 @@ else
     RESET=""
 fi
 
+# check for the existence of a required command
+# throw an error describing the command name when unsatisfied
+# then exit
+i_can_haz() {
+    command_name="$1"
+    if [[ ! -x "$(command -v "${command_name}")" ]]; then
+        reverberate "error" "The required command ${command_name} was not found"
+        reverberate "failure" "${command_name}"
+        reverberate "exit"
+        exit 1
+    fi
+}
+
 # simple privilege check
 check_privilege() {
     if [[ ! "${EUID}" -eq "0" ]];then
@@ -179,7 +192,7 @@ verbosity_level="${verbosity_level}"
 update_now() {
     if [[ -x "$(command -v wget)" ]]; then
         if [[ "${verbosity_level}" -ge "4" ]]; then
-            wget -q --show-progress "${plugin_domain}" -O "${current_dir}/munin-pihole-plugins" || return
+            wget -q --show-progress "${plugin_domain}" -O "${current_dir}/munin-pihole-plugins" || >
             sleep "${hold_duration}"
         else
             wget -q "${plugin_domain}" -O "${current_dir}/munin-pihole-plugins" || return
@@ -388,8 +401,8 @@ install_dependencies() {
     if [[ "${install_webserver}" == "true" ]]; then
         dependency_list+="${webserver_dependencies}"
     fi
-    if [[ -x "$(command -v dpkg-query)" ]]; then
-        if [[ -x "$(command -v apt)" ]]; then
+    if i_can_haz dpkg-query; then
+        if i_can_haz apt; then
             reverberate "info" "Checking for required dependencies"
             for dependency_id in ${dependency_list}; do
                 package_query="$(dpkg-query -W --showformat='${Status}\n' "${dependency_id}" | grep "install ok installed")"
@@ -406,23 +419,13 @@ install_dependencies() {
                     reverberate "success" "${dependency_id}"
                 fi
             done
-        else
-            reverberate "error" "The required command 'apt' was not found"
-            reverberate "failure" "apt"
-            reverberate "exit"
-            exit 1
         fi
-    else
-        reverberate "error" "The required command 'dpkg-query' was not found"
-        reverberate "failure" "dpkg-query"
-        reverberate "exit"
-        exit 1
     fi
 }
 
 # simple wget wrapper
 download() {
-    if [[ -x "$(command -v wget)" ]]; then
+    if i_can_haz wget; then
         if [[ "${verbosity_level}" -ge "4" ]]; then
             wget -q --show-progress "$@" || return
             hold_up
@@ -430,11 +433,6 @@ download() {
             wget -q "$@" || return
             hold_up
         fi
-    else
-        reverberate "error" "The required command 'wget' was not found"
-        reverberate "failure" "wget"
-        reverberate "exit"
-        exit 1
     fi
 }
 
@@ -626,17 +624,12 @@ restart_services() {
         service_list+="${webserver_services}"
     fi
     if [[ -n "${service_list}" ]]; then
-        if [[ -x "$(command -v service)" ]]; then
+        if i_can_haz service; then
             reverberate "info" "Restarting services"
             for service_id in ${service_list}; do
                 service "${service_id}" restart
                 reverberate "success" "${service_id}"
             done
-        else
-            reverberate "error" "The required command 'service' was not found"
-            reverberate "failure" "service"
-            reverberate "exit"
-            exit 1
         fi
     fi
 }
@@ -1519,8 +1512,8 @@ uninstall_function() {
                 fi
             fi
             if [[ "${skip_dependency_check}" == "false" ]]; then
-                if [[ -x "$(command -v dpkg-query)" ]]; then
-                    if [[ -x "$(command -v apt)" ]]; then
+                if i_can_haz dpkg-query; then
+                    if i_can_haz apt; then
                         for dependency_id in ${dependency_list}; do
                             package_query="$(dpkg-query -W --showformat='${Status}\n' "${dependency_id}" | grep "install ok installed")"
                             if [[ -n "${package_query}" ]]; then
