munin-pihole-plugins: minor script update
Changes to be committed:
 - modified:   script/munin-pihole-plugins
   bump script version to v1.0 - we have reached basic function
   warn when the pihole command is not available
   use convoluted path variables everywhere
   leave a dummy external.conf on plugin uninstall
   correct sed format for *_strategy munin.conf edit
   silence globbing when removing existing pihole_* symbolic links

diff --git a/script/munin-pihole-plugins b/script/munin-pihole-plugins
--- a/script/munin-pihole-plugins
+++ b/script/munin-pihole-plugins
@@ -9,11 +9,11 @@ munin_config_dir="${MUNIN_CONFIG_DIR:-/etc/munin}"
 munin_plugin_dir="${MUNIN_PLUGIN_DIR:-/usr/share/munin/plugins}"
 node_plugin_dir="${NODE_PLUGIN_DIR:-$munin_config_dir/plugins}"
 plugin_config_dir="${PLUGIN_CONFIG_DIR:-$munin_config_dir/plugin-conf.d}"
-plugin_list="${PLUGIN_LIST:-blocked cache cache_by_type clients percent queries replies_by_type status unique}"
+plugin_list="${PLUGIN_LIST:-blocked cache cache_by_type clients percent queries replies_by_type status unique_domains}"
 plugin_repo="https://raw.githubusercontent.com/saint-lascivious/munin-pihole-plugins/master"
 proxy_config_dir="${PROXY_CONFIG_DIR:-/etc/lighttpd}"
 proxy_repo="https://raw.githubusercontent.com/saint-lascivious/lighttpd-external-munin-proxy/master"
-script_version="0.6"
+script_version="1.0"
 service_list="lighttpd munin munin-node"
 
 obnoxious_header() {
@@ -23,6 +23,12 @@ obnoxious_header() {
     echo -e "\\e[34;1m  |_|_|_\\_,_|_||_|_|_||_| | .__/_|_||_\\___/_\\___| | .__/_|\\_,_\\__, |_|_||_/__/  "
     echo -e "\\e[36;1m                          |_|                     |_|         |___/             "
     echo -e "\\n\\e[35;1m        A set of Munin plugins for monitoring various Pi-hole statistics        \\e[0m\\n"
+}
+
+check_pihole() {
+    if [[ ! -x "$(command -v pihole)" ]]; then
+        echo -e " * \\e[33;1m[WARNING]\\e[0m Pi-hole was not found"
+    fi
 }
 
 install_dependencies() {
@@ -54,7 +60,7 @@ configure_proxy() {
             rm "$proxy_config_dir"/external.conf || return
         fi
         if [[ -x "$(command -v wget)" ]]; then
-            wget -q --show-progress "$proxy_repo"/etc/lighttpd/external.conf -P "$proxy_config_dir"
+            wget -q --show-progress "$proxy_repo$proxy_config_dir"/external.conf -P "$proxy_config_dir"
         else
             echo -e " * \\e[31;1m[ERROR]\\e[0m The required package 'wget' was not found"
             exit 1
@@ -69,8 +75,8 @@ configure_proxy() {
 configure_munin() {
     if [[ -d "$munin_config_dir" ]]; then
         if [[ -f "$munin_config_dir"/munin.conf ]]; then
-            sed -i '/#html_strategy cron/html_strategy cgi/' "$munin_config_dir"/munin.conf
-            sed -i '/#graph_strategy cron/graph_strategy cgi/' "$munin_config_dir"/munin.conf
+            sed -i "s/#html_strategy cron/html_strategy cgi/g" "$munin_config_dir"/munin.conf
+            sed -i "s/#graph_strategy cron/graph_strategy cgi/g" "$munin_config_dir"/munin.conf
         else
             echo -e " * \\e[31;1m[ERROR]\\e[0m No Munin configuration file found at"
             echo "$munin_config_dir/munin.conf"
@@ -96,7 +102,7 @@ remove_existing() {
     fi
     if [[ -d "$node_plugin_dir" ]]; then
         for plugin_link in "$node_plugin_dir"/pihole_*; do
-                rm "$plugin_link" || return
+                rm "$plugin_link" 2> /dev/null
         done
     else
         echo -e " * \\e[33;1m[WARNING]\\e[0m No Munin node plugin directory found at"
@@ -109,7 +115,7 @@ install_plugins() {
         if [[ -d "$node_plugin_dir" ]]; then
             for plugin_id in $plugin_list; do
                 if [[ -x "$(command -v wget)" ]]; then
-                    wget -q --show-progress "$plugin_repo"/usr/share/munin/plugins/pihole_"$plugin_id" -P "$munin_plugin_dir" || return
+                    wget -q --show-progress "$plugin_repo$munin_plugin_dir/pihole_$plugin_id" -P "$munin_plugin_dir" || return
                 else
                     echo -e " * \\e[31;1m[ERROR]\\e[0m The required package 'wget' was not found"
                     exit 1
@@ -133,7 +139,7 @@ configure_plugins() {
     if [[ -d "$plugin_config_dir" ]]; then
         if [[ ! -f  "$plugin_config_dir/pihole" ]]; then
             if [[ -x "$(command -v wget)" ]]; then
-                wget -q --show-progress "$plugin_repo"/etc/munin/plugin-conf.d/pihole -P "$plugin_config_dir"
+                wget -q --show-progress "$plugin_repo$plugin_config_dir"/pihole -P "$plugin_config_dir"
             else
                 echo -e " * \\e[31;1m[ERROR]\\e[0m The required package 'wget' was not found"
                 exit 1
@@ -181,6 +187,7 @@ Where \\e[33;1mOPTION\\e[0m is \\e[31;1mone\\e[0m of
 
 install_function() {
     obnoxious_header
+    check_pihole
     install_dependencies
     configure_proxy
     configure_munin
@@ -201,6 +208,7 @@ uninstall_function() {
         else
             if [[ -f "$proxy_config_dir"/external.conf ]]; then
                 rm "$proxy_config_dir"/external.conf || return
+                touch "$proxy_config_dir"/external.conf
             fi
         fi
     else
